name: counterfactual_learning
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - requests
  - numpy
  - matplotlib
  - seaborn
  - tqdm
  - scipy
  # - ipykernel
  # - jupyter
